// @ts-ignore: generated by the OpenNext Cloudflare build
import openNextWorker from './.open-next/worker.js'
import scheduledWorker from './workers/send-scheduled'
import { isAuthDisabled, hasDatabaseRuntimeEnv, hydrateRuntimeEnv } from './lib/runtime-env'

type Env = {
  DATABASE_URL: string
  OPENAI_API_KEY: string
  RESEND_API_KEY: string
  DEFAULT_FROM_EMAIL: string
  DEFAULT_FROM_NAME: string
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return openNextWorker.fetch(request, env, ctx)
  },
  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    const runtimeEnv = hydrateRuntimeEnv(env as unknown as Record<string, string | undefined>)
    if (isAuthDisabled(runtimeEnv) || !hasDatabaseRuntimeEnv(runtimeEnv)) {
      return
    }
    return scheduledWorker.scheduled(event, env, ctx)
  },
}
